name: Build lBochs APK

on:
  workflow_dispatch: # Allows you to trigger the build manually with a button click

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Java Development Kit (JDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8' # lBochs requires older Java 8 to compile properly

    - name: Install Android NDK
      run: |
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;21.4.7075529"

    - name: Grant Execute Permissions to Gradle
      run: chmod +x gradlew

    - name: Compile APK with Gradle
      run: ./gradlew assembleDebug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: lBochs-Clean-Build
        path: app/build/outputs/apk/debug/*.apk
        
